SUPABASE_URL = "https://ytpnstmjkawwwwcwdzccw.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl0cG5zdG1qa2F3dndjd2R6Y2N3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzkzNjQxNjUsImV4cCI6MjA5NDk0MDE2NX0.prDRTjCMiuainvloTsPp90GJyrUjghdrsS81rACfXZ0"
APP_PASSWORD = "082613"
